// constants.js
export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';

// courseDetailsConstants.js
export const APPLY_COURSE_REQUEST = 'APPLY_COURSE_REQUEST';
export const APPLY_COURSE_SUCCESS = 'APPLY_COURSE_SUCCESS';
export const APPLY_COURSE_FAILURE = 'APPLY_COURSE_FAILURE';
